package YNA

type YnaHourly struct {
	ID        uint `gorm:"primary_key"`
	DataTime string `gorm:"type:timestamp;"`
	Company_id string `gorm:"type:varchar(45);"`
	Company_name string `gorm:"type:varchar(256);"`
	App_id string `gorm:"type:varchar(45);"`
	App_name string `gorm:"type:varchar(256);"`
	App_company_id string `gorm:"type:varchar(45);"`
	App_apikey string `gorm:"type:varchar(256);"`
	App_platform_id string `gorm:"type:varchar(45);"`
	App_platform_name string `gorm:"type:varchar(256);"`
	App_deleted string `gorm:"type:varchar(45);"`
	Country_id string `gorm:"type:varchar(45);"`
	Country_name string `gorm:"type:varchar(256);"`
	Country_iso string `gorm:"type:varchar(45);"`
	Platform_id string `gorm:"type:varchar(45);"`
	Platform_name string `gorm:"type:varchar(256);"`
	AdNetwork_id string `gorm:"type:varchar(45);"`
	AdNetwork_name string `gorm:"type:varchar(45);"`
	AdUnit_id string `gorm:"type:varchar(45);"`
	AdUnit_name string `gorm:"type:varchar(256);"`
	AdUnit_app_id string `gorm:"type:varchar(45);"`
	AdUnit_company_id string `gorm:"type:varchar(45);"`
	AdUnit_status_id string `gorm:"type:varchar(45);"`
	AdUnit_status_name string `gorm:"type:varchar(45);"`
	Placement_id string `gorm:"type:varchar(45);"`
	Placement_name string `gorm:"type:varchar(45);"`
	Placement_code string `gorm:"type:varchar(45);"`
	AssetType_id string `gorm:"type:varchar(45);"`
	AssetType_name string `gorm:"type:varchar(45);"`
	AssetType_code string `gorm:"type:varchar(45);"`
	Impressions int `gorm:"type:int(11);"`
	Clicks int `gorm:"type:int(11);"`
	RevenueInUSD float64 `gorm:"type:double;"`
	AdsRequested int `gorm:"type:int(11);"`
	AdsReceived int `gorm:"type:int(11);"`
	VideoViews int `gorm:"type:int(11);"`
	VideoStarts int `gorm:"type:int(11);"`
	Video25PViews int `gorm:"type:int(11);"`
	Video50PViews int `gorm:"type:int(11);"`
	Video75PViews int `gorm:"type:int(11);"`
	VideoCompletions int `gorm:"type:int(11);"`
	VideoViewRate float64 `gorm:"type:double;"`
	VideoStartRate float64 `gorm:"type:double;"`
	Video25PRate float64 `gorm:"type:double;"`
	Video75PRate float64 `gorm:"type:double;"`
	VideoCompletionRate float64 `gorm:"type:double;"`
	FillRate float64 `gorm:"type:double;"`
	ECPM float64 `gorm:"type:double;"`
	Ctr float64 `gorm:"type:double;"`
	ImpressionFillRate float64 `gorm:"type:double;"`
}
